<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div>
    <form action="/singUp" method="post">
        <label>
            <input name="email" placeholder="Email">
        </label>
        <label>
            <input name="nickname" placeholder="Имя пользователя">
        </label>
        <label>
            <input name="password" type="password">
        </label>
        <input type="submit" value="SingUp">
    </form>
</div>
</body>
</html>